feature/header - Add header in my-library
Okazaki92/Quattro-Team-project-filmoteka pull request #28
Opened 2023-04-17 18:21 UTC by SylviaStachera

Add header by js

2023-04-18 19:07 UTC, mkubera requested changes
do upiekszenia :-]

2023-04-18 19:07 UTC, mkubera commented on src/js/headerLibrary.js
> +
del line

2023-04-18 19:07 UTC, mkubera commented on src/js/headerLibrary.js
> +  });
- kazdy listener dostaje cb fn
- `toggleBtnActive`, tkora uzywa `classList.toggle` dla obydwu btnow
- `e.preventDefault();` jest zbedne (dos prawdzenia)

2023-04-20 16:13 UTC, Okazaki92 approved these changes
Super, dzięki 😁

2023-04-20 18:44 UTC, merged